### ISSUE TITLE
PEX_ROOT environment variable not working for 2.4.2

### ISSUE THREAD

**Issue by cosmin-balanoiu** [adobe-apiplatform/user-sync.py#474] opened 2019-04-05 15:15 UTC
Setting the PEX_ROOT environment variable no longer works around the MAX_PATH when using 2.4.2. There is a very long path for the cryptography dependency that exceeds the limit even with the set variable. Bumped into this on two customer environments.

**Comment by adorton-adobe** [comment] 2019-04-05 15:26
Thanks, I will take a look.  We may need to pin the dependency for now.

**Comment by adorton-adobe** [comment] 2019-04-05 15:27
Can you let me know if this is the case in python 2.7 as well as 3.6?

**Comment by vossen-adobe** [comment] 2019-04-05 15:39
This was happening for me to on windows 10.  I assumed it was a local issue becausei t was just happening on one machine,  but I guess not.  We could also try to set the long path enabled in registry with the installer for now.

**Comment by adorton-adobe** [comment] 2019-04-05 16:09
The Python installer will do that (at least in the 3.6 installer).  How is the UST installer running the Python installer?  Is there a CLI option we can pass to the Python installer to make it enable long path support?

**Comment by adorton-adobe** [comment] 2019-04-05 16:13
The more I think about it, the clearer it is that we need to pin Cryptography to an older version.  I think we should definitely have the UST installer enable long path support for Windows 10 and Server 2016.  But that won't solve the problem for Server 2012.  

cryptography is required by the umapi-client, so we'll pin the version there and release a new umapi-client, and with it a new UST release.

**Comment by vossen-adobe** [comment] 2019-04-05 18:19
I just pushed an installer update that should resolve for win 10 / 2016 using the registry, but it doesn't work for 2012

**Comment by adorton-adobe** [comment] 2019-04-05 21:00
Turns out the issue is with pycryptodome and not cryptography.  We don't need a umapi-client build, so I will plan to make a new UST release shortly.

**Comment by adorton-adobe** [comment] 2019-04-05 21:58
fixed in v2.4.3

**Closed by adorton-adobe** 2019-04-05 21:58 UTC
