### ISSUE TITLE
Specify two fields for email? 

### ISSUE THREAD

**Issue by christopher-b** [adobe-apiplatform/user-sync.py#613] opened 2020-06-05 23:28 UTC
In the connector config, is it possible to specify two fields for email address, such that if the first field is blank, it uses the second field? Something to the effect of: 

user_email_format: "{mail|secondaryEmail}"

Thanks!

**Comment by Luci2015** [comment] 2020-06-08 06:51
That is not a possibility.
At max, you can activate the extension-config.yml;  inside it you can place a small code to check if that attribute is empty and if it is, make it use the value of a different one.

**Comment by adorton-adobe** [comment] 2020-09-15 17:28
Closing this since the extension config was designed to handle scenarios like this.

@christopher-b please let us know if you need any examples for how this would work.

**Closed by adorton-adobe** 2020-09-15 17:28 UTC
