### ISSUE TITLE
ERROR:lastName validation failure.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#489] opened 2019-05-15 07:21 UTC
My customer has a problem. They get an Error will occur when UST is executed.

Error is below:
2019-05-15 05:34:51 1968 ERROR umapi.action - Error in requestID: action_240 (User: {'user': 'XXXXX@domain.com', 'requestID': 'action_240'}, Command: {'createFederatedID': {'email': 'XXXXX@domain.com', 'option': 'ignoreIfAlreadyExists', 'firstname': 'TEST', 'lastname': ' ', 'country': 'JP'}}): code: "error.internal.create_failed" message: "Could not create person for type 2 or 3. Renga result is FIELD_MIN_LENGTH, Field: lastName validation failure."

Please tell me the solution.
Thanks,

**Comment by Luci2015** [comment] 2019-05-15 07:41
Hmm, I've never seen this before, but I think it refers to that empty last name field inside the createFederatedID command you have there: 
`'lastname': ' '`
Try to add both a first name and a last name to the account and retry the create action.
The tool looks for `sn` and `givenName` attributes by default to pick up the first and last name - make sure these are populated.

**Comment by Tomomi99145** [comment] 2019-05-16 02:15
Thank you for your responce.
The customer can't put some value in there.
Is it always an error if the first name or last name is null?

Depending on the environment, an error may not occur.
What causes this customer to be in error?
I want a hint for a solution.
Regards,

**Comment by vossen-adobe** [comment] 2019-05-16 02:55
Yes, this seems to be the case for any time the field is made up of only whitespace and is NOT empty.  This sets the user attribute for lastname to ' ' instead of None, and I guess this is confusing the UMAPI.  The quick fix would be to add a line to the extension config to check this and set to None if it is just whitespace.

**Comment by jameslockman** [comment] 2019-05-16 03:00
Can you trim the field all the time to remove leading and trailing spaces?

--
James Lockman
Senior Manager, Digital Media Services
Adobe
Jlockman@adobe.com<mailto:Jlockman@adobe.com>
(917) 284-2268 Mobile
Sent from his iPhone

On May 15, 2019, at 10:55 PM, vossen-adobe <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, this seems to be the case for any time the field is made up of only whitespace and is NOT empty. This sets the user attribute for lastname to ' ' instead of None, and I guess this is confusing the UMAPI. The quick fix would be to add a line to the extension config to check this and set to None if it is just whitespace.

**Comment by vossen-adobe** [comment] 2019-05-16 03:03
@jameslockman It's okay with leading and trailing - it's only throwing if it's only spaces.  I'd set the target attribute like

lastname = lastname if lastname.trim() else None

**Comment by Tomomi99145** [comment] 2019-05-16 04:12
Thank you @vossen-adobe @jameslockman 
Can you send me a sample of the extension-config.yml? Because I don't know how to write it.

**Comment by vossen-adobe** [comment] 2019-05-16 04:35
@Tomomi99145 
This ought to do the trick for any field (not just lastname)

https://github.com/vossen-adobe/example_ust_config/blob/master/fix_empty_fields.yml

**Comment by Tomomi99145** [comment] 2019-05-16 05:16
Great!
Thank you for your quick response.
I ask the customer to try it.
I will report the result.
Thanks,

**Comment by vossen-adobe** [comment] 2019-05-16 14:41
@Tomomi99145 keep in mind that SSO will not work for these users

**Comment by Tomomi99145** [comment] 2019-05-17 02:22
@vossen-adobe  Thank you.
I think it's not a problem if Idp can pass the value(Firstname and Lastname) to Adobe even if the value are not registered in Admin Console.
What do you think？

**Comment by vossen-adobe** [comment] 2019-05-17 02:29
@Tomomi99145 

All four attributes need to match exactly for the first login, or SSO will throw unknown user okta error.  It's kind of a catch 22, because while it might work in theory if the field is set to None, it won't work in reality because IDP will not include the attribute in the assertion if it is truly empty.  And on the otherhand, you CAN send out an attribute that is made up of whitespace in the assertion, but you CAN'T set this value in the console by UST, manually, OR by csv.

So at the end of the day, I don't think SSO will work in any case for a user that has a whitespace-only or empty attribute.  The one potential solution which I haven't tested yet asks the question:

Can the IDP be made to send out a truly empty attribute by some extra logic that would make it match, in theory, to the empty field on the admin console? 

And if so, will the okta compare those two attributes and decide the are equal, thereby allowing sign in, or will it treat the comparison as not equal because neither contains any data to compare?

**Comment by Tomomi99145** [comment] 2019-05-23 06:51
@vossen-adobe 

https://github.com/vossen-adobe/example_ust_config/blob/master/fix_empty_fields.yml

I ask the question about the above.
If this script is used, will sync blanks as "None" to Admin Console ?
How about the script below.
ーーーーーーーー
for index in range(len(target_attributes)):
    if not target_attributes[index].strip():
        target_attributes[index] = None
ーーーーーーーー
I would be grateful if you could check it.
Thank you,

**Comment by vossen-adobe** [comment] 2019-05-23 14:25
It will replace anything which is already None  (blank) or with only whitespace as None.  It will work as long as long as the IDP can send some values and the SSO is set for username.  With email setting, empty attributes (present or not) will throw Okta Unknown User error

**Comment by Tomomi99145** [comment] 2019-05-24 00:06
Thank you for your answer.
I will ask my customer to try your script.
Thank you,

**Comment by Tomomi99145** [comment] 2019-07-01 00:12
Hi @vossen-adobe 
Customer tried your code, but got a same error again.
whitespace seems to synced whitespace.

Tried code is below:
https://github.com/vossen-adobe/example_ust_config/blob/master/fix_empty_fields.yml

Are there any other workarounds. I need your help.
Thank you.

**Comment by Luci2015** [comment] 2019-07-05 10:20
@Tomomi99145:
if your Customer is using AD, the first and last name cannot contain just spaces, as AD would strip those off once you create the user setting the givenName and sn attributes to `<not set>` which is already picked up as None for the UST.

Try this change inside extension-config.yml file:
```
after_mapping_hook: |
  gn = source_attributes.get('givenName')
  sn = source_attributes.get('sn')
  if not gn:
      del target_attributes['firstname']
  if not sn:
      del target_attributes['lastname']

 ```
From the UM API standpoint you do not get an error if you create the users without first or last name (or both), but I cannot say what will happen when those users will try to sign in, so better check once this is implemented!

In order for the extension to work, make sure that the user-sync-config.yml file has this line active (no # in front):
```
  extension: extension-config.yml
```

Please test and feedback, especially the login part for those with missing attributes.

**Comment by Tomomi99145** [comment] 2019-07-08 07:44
Thank you for your response.

>if your Customer is using AD, the first and last name cannot contain just spaces, as AD would strip
 >those off once you create the user setting the givenName and sn attributes to <not set> which is
 >already picked up as None for the UST.

I also understand the same, but the customer seems to have a blank sync error.

Can I solve the problem when syncing whitespace?

after_mapping_hook: |
   gn = source_attributes.get ('givenName')
   sn = source_attributes.get ('sn')
   if not gn:
       del target_attributes ['firstname']
   if not sn:
       del target_attributes ['lastname']

**Comment by Luci2015** [comment] 2019-07-08 08:12
try this one and if error continues with "value too short" or similar error, will try to modify this further to  strip the whitespace and then check if it's still None

Again, don't forget to test the sign in once this is implemented.

**Comment by Tomomi99145** [comment] 2019-09-03 01:22
Hi @Luci2015 
My customer tried your solution.
But the error could not be resolved.
Do you have any other solution?
Thank you.
Tomomi

**Comment by Luci2015** [comment] 2019-09-03 05:38
What was the error after implementing the extension change? Still "FIELD_MIN_LENGTH"?

**Comment by Tomomi99145** [comment] 2019-09-03 07:27
The error still "FIELD_MIN_LENGTH".

**Comment by Luci2015** [comment] 2019-09-03 09:04
Hi,

Try this one: 
```
after_mapping_hook: |
  gn = source_attributes.get('givenName').strip()
  sn = source_attributes.get('sn').strip()
  if not gn:
      del target_attributes['firstname']
  if not sn:
      del target_attributes['lastname']
```

If it fails again, please copy the output error and paste here.

**Comment by Tomomi99145** [comment] 2019-09-04 02:44
Hi @Luci2015 
Thank you for your answer.

Can I use your script without changing it.
Do I need to change it to suit customer environment.('firstname','lastname',etc.. )

Tomomi

**Comment by Luci2015** [comment] 2019-09-04 06:44
You should use exactly what was provided and inserted in extension yml file as the "after_mapping_hook: | " statement; no chnage required anywhere. Just make sure the alignement is like you see in the code area of the comment above.

**Comment by Tomomi99145** [comment] 2019-10-10 06:26
Hi @Luci2015
My customer tried your solution.
But error occored again.

Error is below;
-------------------
2019-10-09 15:11:47 4984 DEBUG processor - Target attrs, before: {'email': 'XXX@examole.com', 'username': 'XXX@examole.com', 'domain': 'examole.com', 'firstname': None, 'lastname': 'test', 'country': 'JP'}
2019-10-09 15:11:47 4984 DEBUG processor - Target groups, before: set()
2019-10-09 15:11:47 4984 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\app.py", line 85, in main
    begin_work(config_loader)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\app.py", line 322, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\rules.py", line 171, in run
    self.read_desired_user_groups(directory_groups, directory_connector)
  File "c:\pex\install\user_sync-2.3-py3-none-any.whl.0d3165175054f7d7ed22c445092a54076a10dafa\user_sync-2.3-py3-none-any.whl\user_sync\rules.py", line 374, in read_desired_user_groups
    exec(options['after_mapping_hook'], self.after_mapping_hook_scope)
  File "<per-user after-mapping-hook>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'strip'
2019-10-09 15:11:47 4984 INFO main - ========== End Run (User Sync version: 2.3) (Total time: 0:01:06) 

Please tell me other solution.
Regards,
Tomomi

**Comment by Luci2015** [comment] 2019-10-10 06:57
Try without .strip() portion as I see givenName or sn might come empty:
```
after_mapping_hook: |
  gn = source_attributes.get('givenName')
  sn = source_attributes.get('sn')
  if not gn:
      del target_attributes['firstname']
  if not sn:
      del target_attributes['lastname']
```

**Comment by Tomomi99145** [comment] 2019-10-10 07:45
Thank you for your responce.

Already tryed without .strip().
This is the solution you taught me before.

**Comment by Luci2015** [comment] 2019-10-10 08:17
normally if you have used the above, the 'firstname' would not show up in the dict and the None value would not be a problem; this is why I chose to delete the target_attributes with None or empty value.
I tested with my setup and it worked..
Maybe we can roubleshoot together this Customer's setup?

**Comment by Tomomi99145** [comment] 2019-10-28 00:52
>Maybe we can troubleshoot together this Customer's setup?
I think it's difficult.

However I can onsite troubleshoot at my customer.
Please tell me  what I should be checking for.
For example...
・Run LDAP command directly.

We look forward to your answer.
Tomomi

**Comment by Tomomi99145** [comment] 2019-11-14 00:39
Does anyone have any advise for this problem?
I would appreciate your cooperation.

**Comment by vossen-adobe** [comment] 2019-11-14 01:06
@Tomomi99145 can you tell us what the current problem is? Looks like you resolved the original error by removing strip.  What is the root problem? Is this the case where LastName is a space or empty in ad?

**Comment by Tomomi99145** [comment] 2019-11-15 06:38
@vossen-adobe Thank you for your responce.
The problem is that the user cannot sync when the FirstName or LastName are blank.
The error remains the same.

**Comment by Luci2015** [comment] 2019-11-15 08:01
The provided solutions should work around the missing metadata if they come in as blank or just space char (although AD would already strip the extra spaces, therefore the value can't be just space char(s)). More, the tool accepts None as value for first and last name so it's not a blocking situation, or at least I cannot reproduce the error when I have no values for those fields.
Let's verify by modifying the extension file to contain these lines:
```
after_mapping_hook: |
    gn = source_attributes.get('givenName')
    print('givenName:', gn)
    sn = source_attributes.get('sn')
    print('sn:', sn)
```
In Command Prompt, you'll get the givenName and sn values for each found user. 
Please copy those values for the account with the error and set aside for later.
In your log (hope you run with file_log_level: debug), you'll see lines such as:
```
Source attrs, before:
Target attrs, before:
Source attrs, after:
Target attrs, after:
```
Copy these lines for the erroring account and send a reply with the output from Command Prompt and log file.

**Comment by adorton-adobe** [comment] 2020-09-16 18:48
Closing this as there hasn't been any activity for quite a while.

**Closed by adorton-adobe** 2020-09-16 18:48 UTC
