### ISSUE TITLE
400 error when processing groups

### ISSUE THREAD

**Issue by kirkmawa** [adobe-apiplatform/user-sync.py#409] opened 2018-09-28 18:03 UTC
I'm working on setting up the User Sync tool and when I have it process groups I get an error. I did some further troubleshooting and when I perform a GET request from any client to the `/v2/usermanagement/groups/(org ID)/0` endpoint, the response is a 400 error with the content of:

`{"errorMessage":"For input string: \"878f10ff01babf20a9a51c3cb27713f5c73c2b175ffcfddcbba21f2de407b4ba\""}`

I can confirm that retrieving a list of users from the API works as expected, so there does not seem to be an issue with exchanging a JWT for an access token and making other requests.

**Comment by Luci2015** [comment] 2018-09-28 19:11
What is the error you get in the UST's log? The tool should 'know' how to handle group processing -> have you modified the default values in connector_ldap for group filters?

For the GET call you tried individually, you need at least 2 header files to get a proper response. 
Also I don't think any of the released versions use `/v2/usermanagement/groups/(org ID)/0`

**Comment by kirkmawa** [comment] 2018-09-28 19:31
I should stress this also happens when I run the GroupInformation.py sample script from the umapi-documentation repo. 

In user-sync-config.yml, I have the following group mapping:
```
  groups:
    - directory_group: AdobeLicense-SparkEdu
      adobe_groups:
        - ADSync-AdobeLicense-SparkEdu
```
The ADSync-AdobeLicense-SparkEdu user group already exists in the Adobe Admin Console. 

This behavior happens when group_filter_format is left at the default and when the Active Directory-specific filter in the comments is used.

At the debug log level, this is the trace:

```
2018-09-28 15:14:52 3476 INFO processor - ---------- Start Sync with UMAPI ---------------------------
2018-09-28 15:14:52 3476 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): usermanagement.adobe.io:443
2018-09-28 15:14:53 3476 DEBUG urllib3.connectionpool - https://usermanagement.adobe.io:443 "GET /v2/usermanagement/groups/F392937457474F507F000101@AdobeOrg/0 HTTP/1.1" 400 105
2018-09-28 15:14:53 3476 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\app.py", line 85, in main
    begin_work(config_loader)
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\app.py", line 329, in begin_work
    rule_processor.run(directory_groups, directory_connector, umapi_connectors)
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\rules.py", line 180, in run
    self.create_umapi_groups(umapi_connectors)
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\rules.py", line 482, in create_umapi_groups
    on_adobe_groups = [normalize_string(g['groupName']) for g in umapi_connector.get_groups()]
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\connector\umapi.py", line 150, in get_groups
    return list(self.iter_groups())
  File "c:\users\drew.admin\.pex\install\user_sync-2.4rc1-py3-none-any.whl.8f90403bdc27050d6676fad41c2768fcc63bb1e0\user_sync-2.4rc1-py3-none-any.whl\user_sync\connector\umapi.py", line 154, in iter_groups
    for g in umapi_client.GroupsQuery(self.connection):
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\api.py", line 234, in __next__
    return self.next()
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\api.py", line 230, in next
    return self.query._next_item()
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\api.py", line 214, in _next_item
    self._next_page()
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\api.py", line 205, in _next_page
    self.url_params, self.query_params)
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\connection.py", line 272, in query_multiple
    raise re
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\connection.py", line 264, in query_multiple
    result = self.make_call(query_path)
  File "c:\users\drew.admin\.pex\install\umapi_client-2.11-py2.py3-none-any.whl.a9e91dd5078fbb8e84e1689ac043156cca44f646\umapi_client-2.11-py2.py3-none-any.whl\umapi_client\connection.py", line 460, in make_call
    raise RequestError(result)
umapi_client.error.RequestError: Request Error (400): {"errorMessage":"For input string: \"878f10ff01babf20a9a51c3cb27713f5c73c2b175ffcfddcbba21f2de407b4ba\""}
2018-09-28 15:14:53 3476 INFO main - ========== End Run (User Sync version: 2.4rc1) (Total time: 0:00:12) 
```

**Comment by Luci2015** [comment] 2018-09-28 19:50
Oh, this is in 2.4rc1.. There's no available version for Mac to test. Will need to install a VM.
Does the 2.3 version work for you?

**Comment by Luci2015** [comment] 2018-09-28 21:45
OK, so I did a test on a win machine, on 2.4rc1 but was successful:
`2018-09-28 14:39:55 2684 INFO processor - ---------- Start Sync with UMAPI --------------
2018-09-28 14:39:55 2684 DEBUG urllib3.connectionpool - Starting new HTTPS connection (1): usermanagement.adobe.io:443
2018-09-28 14:39:56 2684 DEBUG urllib3.connectionpool - https://usermanagement.adobe.io:443 "GET /v2/usermanagement/groups/[edited]@AdobeOrg/0 HTTP/1.1" 200 695
2018-09-28 14:39:56 2684 DEBUG umapi - Ran multi-group query: [] {} (page 0: 51 found)
2018-09-28 14:39:56 2684 INFO processor - Auto create user-group enabled: Creating newGroup
2018-09-28 14:39:56 2684 DEBUG processor - Syncing users to umapi...`

Trying to replicate your issue now...

**Comment by kirkmawa** [comment] 2018-09-29 13:17
I can confirm the issue persists this morning. I entered a request at the adobe.io Zendesk instance yesterday and someone from there sent me here.

**Comment by Luci2015** [comment] 2018-09-29 16:54
Thanks for letting me know. I will follow up internally to see if this is something wrong with the service.
In the meantime, I think you can use v2.3 of the tool, as it does not query for existing groups, unlike 2.4rc1.

**Comment by adorton-adobe** [comment] 2018-09-30 23:40
@kirkmawa This doesn't appear to be a UST issue.  I don't know why the adobe.io support team would have sent you here.  Will you please email me the name of the person who referred you here, along with a ticket number if you have one?  I'm going to close this since it can't be replicated, doesn't appear to be a UST bug, and should be investigated by the adobe.io team.

**Closed by adorton-adobe** 2018-09-30 23:40 UTC

**Comment by lesavage** [comment] 2018-10-02 08:38
I can confirm that this is a UMAPI server bug which will be fixed within the next week.
