### ISSUE TITLE
Include in log which IP addresses are unsuccessful with the LDAPS connection

### ISSUE THREAD

**Issue by mmiddlet** [adobe-apiplatform/user-sync.py#843] opened 2024-02-29 15:45 UTC
When a connection to a single DNS server or domain controller fails, ideally, the unsuccessful IP addresses should be added to the log. This would be very helpful.

Of course, if a connection to a single DNS server or domain controller fails, ideally the application should have the intelligent logic coded in to attempt to connect to an alternate DNS server or domain controller.

**Comment by adorton-adobe** [comment] 2024-04-02 17:04
duplicate of #841

**Closed as not planned by adorton-adobe** 2024-04-02 17:04 UTC
