### ISSUE TITLE
Failing to create users of type FederatedID

### ISSUE THREAD

**Issue by petersseth86** [adobe-apiplatform/user-sync.py#571] opened 2020-02-24 20:04 UTC
Python 3.6.8 / User Sync Tool v2.5.0

New users are not able to be created...log just shows:

2020-02-24 13:14:58 3192 ERROR umapi.action - Error in requestID: action_2 (User: {'user': 'sethtest@test.com', 'requestID': 'action_2'}, Command: {'createFederatedID': {'email': 'sethtest@test.com', 'option': 'ignoreIfAlreadyExists', 'firstname': 'Seth', 'lastname': 'Test', 'country': 'US'}}): code: "error.internal.create_failed" message: "Could not create person of type createFederatedID"

**Comment by adorton-adobe** [comment] 2020-02-24 20:19
Is `sethtest@test.com` the literal email address of the account you are trying to create? If so, that could be why the call is failing. You can only create Federated users for domains claimed by or trusted to your Admin Console organization. However, the error in that case would probably be different.

**Comment by petersseth86** [comment] 2020-02-24 20:38
It is not, I just wasn't sure who all could see what.

**Comment by adorton-adobe** [comment] 2020-02-24 20:45
Is the email domain of the user one that is claimed and associated with a federated directory? If so, is that directory fully configured and active? Is it a generic SAML directory, or does it use the Azure AD or Google connectors?

**Comment by petersseth86** [comment] 2020-02-24 20:52
Yes, the email domain is the one claimed and associated with our federated directory. It is fully configured and active. We sync from on-premise AD. Was working normally a week or so ago using Python 2.7.14 with User Sync Tool 2.2.2rc2. I installed Python 3.6.8 and updated to User Sync Tool v2.5 compiled for 3.6.8. I get no errors of any kind until a user actually needs to be created.

**Comment by petersseth86** [comment] 2020-02-24 20:56
Sorry, yes it is a generic SAML directory.

**Comment by adorton-adobe** [comment] 2020-02-25 01:15
Strange. I'll take a look, but I've never seen this error before and I'm not sure what to make of it.

@Luci2015 have you seen this error before?

**Comment by Luci2015** [comment] 2020-02-25 06:07
I've seen other report about 2 days ago, but I waited to see some logs and config files to be sure that the default type wasn't messed up in the connector-ldap or user-sync-config.yml
I guess this confirms it must be an UMAPI issue here. I'll follow up internally.

@petersseth86: can you please send an email to wwds@adobe.com with your OrgId and the debug level log you get from your usual run? Thanks!

**Comment by adorton-adobe** [comment] 2020-02-25 15:09
Thanks Lucian! I am going to close this issue as this appears to be a UMAPI issue and not a UST issue. Feel free to re-open it if anything points back to the UST as the root cause.

**Closed by adorton-adobe** 2020-02-25 15:09 UTC
