### ISSUE TITLE
The Adobe User Sync Tool finds the username (E00#)  in Directory Users, But it will no update users email address after name change.

### ISSUE THREAD

**Issue by eaguilar23** [adobe-apiplatform/user-sync.py#835] opened 2023-11-28 22:51 UTC
We have the sync tool configured to use "username" (E00# in our case) as the ID for users. Problem is when user changes preferred name which changes the users email address the sync tool does not update the email address.

Can we please allow to the sync tool to modify an existing account's email address.

![User email Change](https://github.com/adobe-apiplatform/user-sync.py/assets/105303003/1fd7abb9-4a9e-4134-a7f9-d57e03c7e2a9)

![User email Change 2](https://github.com/adobe-apiplatform/user-sync.py/assets/105303003/9f1547ce-671a-4dc4-b9d8-80531b13b4be)

**Comment by adorton-adobe** [comment] 2024-04-02 16:00
This appears to be a duplicate of #827

**Closed as not planned** 2024-04-02 16:00 UTC
