### ISSUE TITLE
Adobe_Console Module Not Found

### ISSUE THREAD

**Issue by WLDONLEY** [adobe-apiplatform/user-sync.py#631] opened 2020-09-11 03:31 UTC
Having an issue when configuring the User-Sync tool to utilize the Adobe Console connector it gives me an error of:

_ModuleNotFoundError: No module named 'user_sync.connector.directory_adobe_console'_

I have configured this same tool to use the Okta connector and that works as expected. I worked with an Adobe support member to walk through the configuration steps and we seemed to be looking good. 

Any assistance or direction on this would be greatly appreciated.

OS: Ubuntu

[DEBUG.log](https://github.com/adobe-apiplatform/user-sync.py/files/5205741/DEBUG.log)

Sincerely,

William

**Comment by Luci2015** [comment] 2020-09-14 09:49
Looks like the module is missing from the build. A manual build for Ubuntu needs to be made via "make" would help to obtain the working user-sync file.

**Comment by adorton-adobe** [comment] 2020-09-14 13:27
Duplicate of #605 

This fix will be published with v2.6.1. In the meantime, you can make a build of v2 if you need this fix now. We've revised the build instructions on the README - please refer to that and let me know if you have any questions.

**Closed by adorton-adobe** 2020-09-14 13:27 UTC
