### ISSUE TITLE
How to use the --user-filter when I set user_email_format to '{cn}@domain.com'.

### ISSUE THREAD

**Issue by Tomomi99145** [adobe-apiplatform/user-sync.py#464] opened 2019-03-13 03:23 UTC
The user_email_format has been set to '{cn}@domain.com'.
What kind of value should I set the command option when UST execution(use the --user-filter)?

--user-filter "{cn}@domain.com" or  --user-filter "{cn}"

Both did not run correctly. 
Number of directory users selected for input is "0".

please tell me the solution.

**Comment by Luci2015** [comment] 2019-03-13 07:04
when you set user_email_format like that, the tool would look for the 'cn' attribute inside the LDAP for given user and will construct the mail by adding '@domain.com' to it. That value is next used to populate the mail value in Admin Console.
{cn} might not be the best choice here, since it may contain spaces and other special chars, so a valid email cannot be constructed in that case. Maybe you should look for something else that makes unique the user in the directory (sAMAccountName, some user ID, or anything else that can be used)?

If you get 0 results for directory users found is because the applied filters return 0 results in targeted groups. There are so many causes to get 0 results, but the ones that depend on the tool's data input could be:
- base_dn value is too restrictive (maybe set that just to the DC=, not set it to some OU path), so both users and groups are not discovered under that path then run the tool with '--users mapped' so that only users from provided groups get returned, instead of all base_dn users found.
- you have modified the default filters inside connector-ldap (most of the times they do exactly what you need)
- you have targeted a parent group for other nested groups in user-sync-config, but the ldap filter in connector-ldap ( group_member_filter_format) is still the default for flat groups query
- user account in the ldap connector does not have enough rights to extract the users from the provided_base_dn 

Add to this list a lot of others ldap settings that might prevent user extraction (replication issues, OU rights, specific limits,  etc..)

You do not need to provide a user-filter in command line for this problem to go away. Just fix the root cause: why your users can't be extracted from the directory

**Comment by Tomomi99145** [comment] 2019-03-14 00:05
Thank you for your answer.

In my customer's AD, the only attribute that makes unique the user is {cn} . 
It does not contain spaces and other special chars.
Can I still not use {cn} in --user-filter?

**Comment by vossen-adobe** [comment] 2019-03-14 21:27
You shouldn't need the --user-filter for anything, unless I'm misunderstanding.  If you set the email format to {cn}@domain, then the tool should work just like normal except for the different email addresses.  No need to specify an additional filter.

**Comment by adorton-adobe** [comment] 2019-04-10 19:56
Looks like this has been addressed.  Closing.

**Closed by adorton-adobe** 2019-04-10 19:56 UTC
