### ISSUE TITLE
Call UMAPI Client directly and don't create JSON structures for UMAPI operations

### ISSUE THREAD

**Issue by phil-levy** [adobe-apiplatform/user-sync.py#88] opened 2017-03-17 04:00 UTC
Call UMAPI client directly as user operations are identified.  It will automatically bundle operations and run them in batches.  Clean up code so there isn't duplicate functionality for creating and managing JSON requests; let UMAPI client handle this.

**Comment by adobeDan** [comment] 2017-03-24 23:40
@ianmak I'd rather have you working on something else.  Look for assignments coming your way.

**Comment by adobeDan** [comment] 2017-03-28 21:52
Looks like this is not needed after all.  The UMAPI client is already doing the batching and command execution and error reporting.  The extra layer of the `ActionManager` is doing useful error checking and generating readable action identifiers which make for better logging.  The extra layer of the `DashboardConnector` is needed to translate the user-sync options into acceptable UMAPI connection setup parameters.  The one thing that could really go away is the `Commands` object, which is a very thin wrapper around the UMAPI functional layer.  But it sort of serves a useful purpose in doing error checking and removal of unused parameters.  Removing it would likely complicate the callers unnecessarily.  So I'm marking this as designed and closing it.

**Closed by adobeDan** 2017-03-28 21:52 UTC
Labels: as designed
