### ISSUE TITLE
Dashboard Group not removed if unmapped directory user not in input set

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/user-sync.py#42] opened 2017-03-01 22:23 UTC
If you remove an active AD user from an AD group that is being mapped for user sync,
PLC does not get removed from the user.

However, if I disabled AD user that will remove PLC in the console just fine

**Comment by adobeDan** [comment] 2017-03-01 22:31
@bhunut-adobe This looks like it might be a misunderstanding of intended functionality as opposed to a bug.  Please attach your user-sync-config.yml (no credentials please), the exact command line invocation you used, and the DEBUG-level log.  (You may have to add .txt to all these files in order to attach them.)

**Comment by bhunut-adobe** [comment] 2017-03-02 00:03
If the user is no longer a member of an AD group shouldn't the user right to the product get revoke also?

I can see a scenario where an employee goes from Creative to HR department and now no longer need Creative Cloud product for the role.

I ran the following command:

`./user-sync --process-groups --users group "SG-Adobe-All-App"`

[user-sync-config.txt](https://github.com/adobe-apiplatform/user-sync.py/files/812354/user-sync-config.txt)
[2017-03-01.txt](https://github.com/adobe-apiplatform/user-sync.py/files/812355/2017-03-01.txt)

**Comment by phil-levy** [comment] 2017-03-02 04:30
In the log I see sync removing jdoe1 from the group.  Assuming this is after removing them from the directory, this looks like correct removal behavior as you were expecting.

**Comment by bhunut-adobe** [comment] 2017-03-02 19:09
Jdoe1 was removed after I disabled the AD account.

Jdoe2 is still an active account but only removed from the AD group. Jdoe2 PLC did not get remove after the sync. 

I ran the same parameters for both cases.

**Comment by adobeDan** [comment] 2017-03-03 08:15
Kevin, can you reproduce this with input from a CSV file instead of AD?  That way you could upload the CSV so we can see the exact user details.

**Comment by phil-levy** [comment] 2017-03-03 08:20
What AD groups are the 2 user accounts in?  I can't tell what users would be selected by --users group "SG-Adobe-All-App"

**Comment by bhunut-adobe** [comment] 2017-03-03 17:33
Here are the current user detail in AD

GivenName : Joe
SurName   : Doe 1
Mail      : jdoe1@ccestestdomain.com
Country   : US
MemberOf  : {CN=SG-Adobe-All-App,OU=Groups,OU=CCESTest Users,DC=ccestestdomain,DC=com}
Enabled   : False

GivenName : Joe
SurName   : Doe 2
Mail      : jdoe2@ccestestdomain.com
Country   : US
MemberOf  : {}
Enabled   : True


1st Sync - Jdoe1 and Jdoe2 are enabled and in SG-Adobe-All-App group in AD. They both got provisioned in Admin Console with correct PLC. 

2nd Sync - Disabled Jdoe1 in AD but still in the group. Jdoe1 PLC get removed from Admin Console.

3rd Sync - Removed JDoe2 from SG-Adobe-All-App AD group. PLC did not get remove.

**Comment by phil-levy** [comment] 2017-03-06 23:20
After staring at this some more, there probably is a bug here and also the need to specify more crisply that the test is done based on the user set specified as determined by the ldap query, the --users option and any --user-filter that is included.  We'll work on it.

**Comment by adobeDan** [comment] 2017-03-06 23:45
@bhunut-adobe are you using v1.0 of User Sync or are you using v1.1.1?  Because this behavior looks like #27 which was present in v1.0 but not in v1.1.1.  Can you please do one more sync run in v1.1.1 to make sure?

**Comment by bhunut-adobe** [comment] 2017-03-08 23:51
@adobeDan  I am using 1.1.1. I rerun it and the same result.

**Comment by adobeDan** [comment] 2017-03-10 21:59
I think I have a line on this one.  Assigning it to me.

**Comment by adobeDan** [comment] 2017-03-12 21:35
This is fixed and waiting for merge into v1.

**Closed** 2017-03-13 17:07 UTC
