### ISSUE TITLE
I get umapi.primary.action error when trying to add users to User Group

### ISSUE THREAD

**Issue by raymond-ensemble** [adobe-apiplatform/user-sync.py#253] opened 2017-07-05 20:36 UTC
I get this error when I tried to sync users from a csv file, where the users are in Product and User groups.

> 2017-07-05 13:25:51 76992 ERROR umapi.primary.action - Error in requestID: action_1 (User: {'requestID': 'action_1', 'user': u'ccewin02@ensemble.ca'}, Command: {'add': {'product': ['ensemble test', 'testgroup', 'default adobe document cloud for enterprise configuration', 'default all apps plan - 100 gb configuration', 'default adobe enterprise support program configuration', 'ensemble test 2', 'default photoshop cc - 100 gb configuration']}}): code: "error.internal.add" message: "add [ccewin02@ensemble.ca] to product group testgroup failed: "
2017-07-05 13:25:51 76992 ERROR umapi.primary.action - Error in requestID: action_2 (User: {'requestID': 'action_2', 'user': u'ccewin2@ensemble.ca'}, Command: {'add': {'product': ['ensemble test', 'ensemble test 2']}}): code: "error.internal.add" message: "add [ccewin2@ensemble.ca] to product group Ensemble Test 2 failed: "

The User Group "Ensemble Test", "testgroup", and "Ensemble Test 2" already exists in the Adobe dashboard.

[2017-07-05.txt](https://github.com/adobe-apiplatform/user-sync.py/files/1125960/2017-07-05.txt)

**Comment by adobeDan** [comment] 2017-07-10 20:05
The "error.internal.add" error code suggests this was due to instability in the connection between the UMAPI server and the back-end server which actually does the add of the user to the group.  If you can repro this failure please attach a debug log and I will pass it on to the server team.

**Comment by raymond-ensemble** [comment] 2017-07-11 17:25
I just retried it and it seems to be working fine now.

However, I'm not sure if it's related to the same issue, but when I tried to open the Admin Console Users page on my browsers (Firefox, Chrome), I would get an infinite spinner. I can open other pages (User Groups, Admins, Overview, etc) without any issue.

**Comment by jameslockman** [comment] 2017-07-11 17:26
Your console may have been updated to the new Console. Try clearing your browser cache and reload the page.

James

James Lockman  | Manager, Digital Media Services  |  Adobe
p. 917.934.0849<tel:19179340849>  |  c. 917.284.2268<tel:19172842268>  |  @jameslockman<http://twitter.com/jameslockman>  |  blog<http://blogs.adobe.com/jlockman>  |  jlockman@adobe.com<mailto:jlockman@adobe.com>

**Comment by raymond-ensemble** [comment] 2017-07-11 17:33
I'm still getting the spinner after clearing cache. I also tried it on Incognito chrome browser, but it's the same.

**Comment by adobeDan** [comment] 2017-07-11 19:50
I believe you will need to be VPN'd in to Adobe to manage this org, because it's been converted to use the new Console UI (aka One Console) and I don't think we are allowing that outside the firewall yet.  I know that @chesterl86 has gotten VPN credentials for a number of you.

**Comment by adobeDan** [comment] 2017-07-13 07:12
Closing since the original symptom does not reproduce.  @raymond-ensemble, feel free to contact me via email if you continue to have issues with the console.

**Closed by adobeDan** 2017-07-13 07:12 UTC
Labels: cannot reproduce
