### ISSUE TITLE
UST is case sensitive, but UMAPI is not

### ISSUE THREAD

**Issue by maplatoff** [adobe-apiplatform/user-sync.py#529] opened 2019-08-21 19:37 UTC
UST does not make the correct call to UMAPI service when the account and username are case-insensitive-equal, but differ in case.  UST makes a call with username and mail address, but UMAPI aborts with a message that says that only the mail address should be supplied, aborting the sync cycle.   When the case is corrected, the sync proceeds.  UST and UMAPI should treat case consistently.

**Comment by adorton-adobe** [comment] 2019-08-21 19:45
Can you please let me know which version of the tool you're using?  Please also provide the error you're getting and a list of steps to reproduce.

**Comment by adorton-adobe** [comment] 2019-08-21 19:46
And please also provide your UST version, Python version, and operating system.

**Comment by maplatoff** [comment] 2019-08-22 23:12
We're using Windows Server 2016, Python 3.6.2 and UST 2.4:

Thanks.

**Comment by adorton-adobe** [comment] 2019-08-22 23:14
Try UST v2.5.  It fixes an issue related to case-sensitivity and email addresses.

**Comment by adorton-adobe** [comment] 2020-09-16 14:12
Closing this since there hasn't been any followup in over a year. Please re-open if this behavior persists in the latest version of the tool.

**Closed by adorton-adobe** 2020-09-16 14:12 UTC
